FROM nginx:1.20-alpine

# Copy documentations files
COPY ./docs /usr/share/nginx/html/docs
COPY ./icon.png /usr/share/nginx/html/icon.png
COPY ./CONTRIBUTING.md /usr/share/nginx/html/CONTRIBUTING.md
COPY ./index.html /usr/share/nginx/html/index.html
COPY ./LICENCE.md /usr/share/nginx/html/LICENCE.md
COPY ./README.md /usr/share/nginx/html/README.md
